/**
 * 日程标准模板 · stage_templates（本地 PostgreSQL 官方数据，2026-08-31 实查）
 * D-day 发动机：先定 Dday(elections.el_election_date)，按 st_day_offset 倒排生成 election_stages。
 * 村/社区共用同一套流程（阶段内按组织类型区分）。
 */
export interface StageTemplate {
  key: string; // 如 D-35 / D0 / D+1~+10
  name: string;
  offset: number; // 相对 D 日起始天数偏移（-35 = D-35，0 = D 日，+1 = D+1）
  offsetEnd?: number; // 区间阶段结束偏移
  work: string; // st_core_work
  sys_action: string; // st_sys_action
  announcement: string; // st_announcement（描述）
  announcements: string[]; // 关联公告模板编号（见 announcementTemplates）
  review: string; // st_review_round
  material: string; // st_material_type
}

export const STAGE_TEMPLATES: StageTemplate[] = [
  {
    key: 'D-35',
    name: '前期筹备',
    offset: -35,
    work: '村两委联席会议定班子职数；离任财务审计村务公示；筹备选委会推选',
    sys_action: '无候选人材料操作，仅提案审批模块提交换届启动申请',
    announcement: '无',
    announcements: [],
    review: '提案审批',
    material: '换届启动申请',
  },
  {
    key: 'D-34',
    name: '成立选委会',
    offset: -34,
    work: '推选5-9人选委会；选委会分工；表决选举办法',
    sys_action: '无材料候选人操作，仅母版配置基础信息',
    announcement: '1号、2号、3号公告',
    announcements: ['1', '2', '3'],
    review: '选委会备案',
    material: '选委会名单',
  },
  {
    key: 'D-33~-29',
    name: '选民登记',
    offset: -33,
    offsetEnd: -29,
    work: '逐户登记年满18周岁无剥夺政治权利村民；登记外出老弱病残流动票箱人员',
    sys_action: '仅选民名册录入，不开放材料上报候选人流程',
    announcement: '持续张贴3号公告',
    announcements: [],
    review: '',
    material: '',
  },
  {
    key: 'D-28~-24',
    name: '公示选民名单',
    offset: -28,
    offsetEnd: -24,
    work: '汇总全部选民，开启5天异议申诉期',
    sys_action: '无材料候选人操作',
    announcement: '4号选民名单公告',
    announcements: ['4'],
    review: '选民资格审核',
    material: '选民名册',
  },
  {
    key: 'D-23~-21',
    name: '受理选民申诉',
    offset: -23,
    offsetEnd: -21,
    work: '核查资格异议，更正选民名册',
    sys_action: '无材料候选人操作',
    announcement: '选民名单更正补充公告',
    announcements: [],
    review: '异议核查',
    material: '选民名单更正',
  },
  {
    key: 'D-20~-16',
    name: '代表选举',
    offset: -20,
    offsetEnd: -16,
    work: '村：村民代表和小组长；居：居民代表和户代表',
    sys_action: '代表和小组长选举结果录入',
    announcement: '5号、6号、6-1号公告',
    announcements: ['5', '6', '6-1'],
    review: '选举结果确认',
    material: '代表名单、小组长名单',
  },
  {
    key: 'D-15',
    name: '候选人提名启动',
    offset: -15,
    work: '发布7号提名公告；开放组织推荐、个人自荐两类提名',
    sys_action: '候选人提名开启；材料上报同步开启；r1材料完整性审核开始',
    announcement: '7号提名公告',
    announcements: ['7'],
    review: '第一轮-材料完整性审核',
    material: '自荐表、身份证、个人简历、无犯罪记录证明、组织推荐函',
  },
  {
    key: 'D-14',
    name: '候选人提名延续',
    offset: -14,
    work: '持续接收组织推荐、群众自荐材料',
    sys_action: '候选人提名；材料上报；材料审核持续',
    announcement: '持续张贴7号公告',
    announcements: [],
    review: '第一轮-材料完整性审核',
    material: '候选人提名相关材料',
  },
  {
    key: 'D-13',
    name: '初步候选人汇总+镇级初审',
    offset: -13,
    work: '汇总全部人员；镇级资格初审；选委会递补',
    sys_action: '提名收尾；r1完成；r2镇级初审；关闭材料上报入口',
    announcement: '8号初步候选人名单公告、2-1号选委会递补公告',
    announcements: ['8'],
    review: '第二轮-镇级资格初审',
    material: '初步候选人汇总名单',
  },
  {
    key: 'D-12~-10',
    name: '竞选预选',
    offset: -12,
    offsetEnd: -10,
    work: '超差额职位召开代表会议无记名预选，确定正式候选人',
    sys_action: '预选投票组织与结果录入',
    announcement: '预选办法公告、预选结果公告',
    announcements: [],
    review: '预选结果确认',
    material: '预选结果',
  },
  {
    key: 'D-9~-5',
    name: '区级11部门联审、党委考察',
    offset: -9,
    offsetEnd: -5,
    work: '多部门资格核查，党委考察筛选正式候选人',
    sys_action: '暂停新增材料上报；r3区级多部门联审；r4党委考察',
    announcement: '无',
    announcements: [],
    review: '第三轮-区级联审、第四轮-党委考察',
    material: '',
  },
  {
    key: 'D-4',
    name: '正式候选人公示',
    offset: -4,
    work: '联审收尾，确定并公示正式候选人',
    sys_action: '四轮全过转正式候选人；关闭材料上报和新增提名入口',
    announcement: '9号正式候选人名单公告',
    announcements: ['9'],
    review: '最终确认',
    material: '',
  },
  {
    key: 'D-3~-2',
    name: '投票竞选筹备',
    offset: -3,
    offsetEnd: -2,
    work: '确定监票、计票、流动票箱、代写人员',
    sys_action: '竞选筹备阶段公示配套规则',
    announcement: '10~14号公告',
    announcements: ['10', '11', '12', '13', '14'],
    review: '工作人员备案',
    material: '选举工作人员名单、流动票箱名单、委托投票名单、代写名单',
  },
  {
    key: 'D-1',
    name: '投票竞选筹备',
    offset: -1,
    work: '印制选票，布置票箱',
    sys_action: '竞选筹备阶段',
    announcement: '15号无效票认定规则公告',
    announcements: ['15'],
    review: '',
    material: '',
  },
  {
    key: 'D0',
    name: '正式投票选举',
    offset: 0,
    work: '现场集中+流动票箱投票；当众开箱计票；当场公布结果',
    sys_action: '正式选举（投票当日）；录入线下投票结果更新当选人员',
    announcement: '16号选举结果公告、17号村务监督委员会公告',
    announcements: ['16', '17'],
    review: '结果确认备案',
    material: '选举结果报告',
  },
  {
    key: 'D+1~+10',
    name: '结果备案、新旧班子交接',
    offset: 1,
    offsetEnd: 10,
    work: '整理选举档案；公章、财务、档案、固定资产交接',
    sys_action: '竞选流程结束仅归档；全流程结束所有材料候选人模块锁定只读',
    announcement: '无',
    announcements: [],
    review: '归档确认',
    material: '选举档案、交接清单',
  },
];
